<a href="https://colab.research.google.com/github/Sautam05/Pandas/blob/main/Data_Cleaning_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Cleaning Assignment (Pandas)

Dataset: **movies_dataset.csv**

Complete all questions using Pandas.

## Q1. Import pandas and load the dataset.

In [2]:
import pandas as pd
import numpy as np

df = pd.read_csv("movies_dataset.csv")

## Q2. Display first 10 rows.

In [3]:
df.head(10)

,Movie_ID,Title,Genre,Release_Year,Rating,Duration,Director,Country,Language,Budget,Revenue,Platform,Age_Rating,Added_Date,Status
0,1,NaN,Romance,2019,8.5,166 min,Director 24,USA,Spanish,$35M,"338,517",Disney+ Hotstar,U,18-04-2025,Upcoming
1,2,The Batman,Action,2024,8.4,123 min,Director 9,UK,Hindi,$192M,"489,099",Amazon Prime,A,20-05-2020,Upcoming
2,3,Jawan,Acton,2020,8.0,126 min,Director 19,Canada,NaN,NaN,"891,296",Netflix,U/A,28-02-2023,Upcoming
3,4,Moana,Horror,2020,6.3,167 min,Director 21,USA,Spanish,$293M,"267,473",Amazon Prime,A,21-12-2024,Released
4,5,KGF,Sci-Fi,2024,NaN,120 min,Director 13,Japan,English,$181M,"611,405",Disney+ Hotstar,PG-13,05-05-2021,Released
5,6,RRR,Scifi,2021,9.8,97 min,Director 17,NaN,English,$76M,"263,811",Disney+ Hotstar,PG-13,20-02-2023,Upcoming
6,7,Moana,Action,2023,8.3,148 min,Director 25,Japan,NaN,$170M,"564,003",Disney+ Hotstar,A,17-03-2024,Released
7,8,Pushpa,Sci-Fi,2019,5.8,179 min,Director 17,India,Spanish,$29M,"471,899",Amazon Prime,U/A,02-04-2024,Released
8,9,Titanic,Acton,2024,8.2,150 min,Director 6,Japan,Spanish,$236M,"652,773",Disney+ Hotstar,U/A,23-05-2023,Upcoming
9,10,Moana,Sci-Fi,2019,NaN,82 min,Director 19,Canada,Spanish,$56M,"160,234",Netflix,U,28-06-2020,Released

## Q3. Display last 10 rows.

In [4]:
df.tail(10)

,Movie_ID,Title,Genre,Release_Year,Rating,Duration,Director,Country,Language,Budget,Revenue,Platform,Age_Rating,Added_Date,Status
295,296,Avatar,Comedy,2021,NaN,134 min,Director 13,UK,NaN,$248M,"419,340",Netflix,U,25-08-2024,Released
296,297,Titanic,Animation,2018,8.3,170 min,Director 25,NaN,HINDI,$134M,"731,264",Amazon Prime,PG-13,06-12-2025,Upcoming
297,298,KGF,Animation,2018,7.2,101 min,Director 10,india,Spanish,$280M,"937,731",Netflix,A,18-11-2020,Upcoming
298,299,Moana,Scifi,2019,9.7,129 min,Director 3,india,Hindi,$240M,"545,580",Amazon Prime,U/A,06-11-2025,Released
299,300,Joker,Horror,2022,7.1,119 min,Director 13,USA,Spanish,$214M,"760,676",Netflix,U,07-03-2024,Released
300,1,NaN,Romance,2019,8.5,166 min,Director 24,USA,Spanish,$35M,"338,517",Disney+ Hotstar,U,18-04-2025,Upcoming
301,2,The Batman,Action,2024,8.4,123 min,Director 9,UK,Hindi,$192M,"489,099",Amazon Prime,A,20-05-2020,Upcoming
302,3,Jawan,Acton,2020,8.0,126 min,Director 19,Canada,NaN,NaN,"891,296",Netflix,U/A,28-02-2023,Upcoming
303,4,Moana,Horror,2020,6.3,167 min,Director 21,USA,Spanish,$293M,"267,473",Amazon Prime,A,21-12-2024,Released
304,5,KGF,Sci-Fi,2024,NaN,120 min,Director 13,Japan,English,$181M,"611,405",Disney+ Hotstar,PG-13,05-05-2021,Released

## Q4. Print shape.

In [5]:
print(df.shape)

(305, 15)

## Q5. Print column names.

In [6]:
print(df.columns)

Index(['Movie_ID', 'Title', 'Genre', 'Release_Year', 'Rating', 'Duration',
       'Director', 'Country', 'Language', 'Budget', 'Revenue', 'Platform',
       'Age_Rating', 'Added_Date', 'Status'],
      dtype='object')

## Q6. Use info().

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 305 entries, 0 to 304
Data columns (total 15 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Movie_ID      305 non-null    int64
 1   Title         282 non-null    object
 2   Genre         305 non-null    object
 3   Release_Year  305 non-null    int64
 4   Rating        278 non-null    float64
 5   Duration      305 non-null    object
 6   Director      305 non-null    object
 7   Country       272 non-null    object
 8   Language      240 non-null    object
 9   Budget        270 non-null    object
 10  Revenue       282 non-null    object
 11  Platform      305 non-null    object
 12  Age_Rating    305 non-null    object
 13  Added_Date    305 non-null    object
 14  Status        305 non-null    object
dtypes: float64(1), int64(2), object(12)
memory usage: 35.9+ KB

## Q7. Use describe().

In [8]:
df.describe()

         Movie_ID  Release_Year      Rating
count  305.000000    305.000000  278.000000
mean   148.081967   2021.108197    7.466547
std     88.052447      2.002818    1.321495
min      1.000000   2018.000000    5.000000
25%     72.000000   2019.000000    6.500000
50%    148.000000   2021.000000    7.500000
75%    224.000000   2023.000000    8.500000
max    300.000000   2024.000000    9.800000

## Q8. Find missing values.

In [9]:
df.isnull().sum()

Movie_ID         0
Title           23
Genre            0
Release_Year     0
Rating          27
Duration         0
Director         0
Country         33
Language        65
Budget          35
Revenue         23
Platform         0
Age_Rating       0
Added_Date       0
Status           0
dtype: int64

## Q9. Check duplicate rows.

In [10]:
df[df.duplicated()]

,Movie_ID,Title,Genre,Release_Year,Rating,Duration,Director,Country,Language,Budget,Revenue,Platform,Age_Rating,Added_Date,Status
300,1,NaN,Romance,2019,8.5,166 min,Director 24,USA,Spanish,$35M,"338,517",Disney+ Hotstar,U,18-04-2025,Upcoming
301,2,The Batman,Action,2024,8.4,123 min,Director 9,UK,Hindi,$192M,"489,099",Amazon Prime,A,20-05-2020,Upcoming
302,3,Jawan,Acton,2020,8.0,126 min,Director 19,Canada,NaN,NaN,"891,296",Netflix,U/A,28-02-2023,Upcoming
303,4,Moana,Horror,2020,6.3,167 min,Director 21,USA,Spanish,$293M,"267,473",Amazon Prime,A,21-12-2024,Released
304,5,KGF,Sci-Fi,2024,NaN,120 min,Director 13,Japan,English,$181M,"611,405",Disney+ Hotstar,PG-13,05-05-2021,Released

## Q10. Remove duplicate rows.

In [11]:
df.drop_duplicates(inplace=True)

## Q11. Remove extra spaces from Title.

In [12]:
df['Title'] = df['Title'].str.strip()

## Q12. Convert Title to Proper Case.

In [13]:
df['Title'] = df['Title'].str.title()

## Q13. Correct Genre spellings (Acton→Action, Scifi→Sci-Fi, Romnce→Romance).

In [14]:
df['Genre'] = df['Genre'].replace({
    'Acton': 'Action',
    'Scifi': 'Sci-Fi',
    'Romnce': 'Romance'
})

## Q14. Convert Country to upper case.

In [15]:
df['Country'] = df['Country'].str.upper()

## Q15. Convert Language to lower case.

In [16]:
df['Language'] = df['Language'].str.lower()

## Q16. Convert Rating to float.

In [17]:
df['Rating'] = df['Rating'].astype(float)

## Q17. Remove 'min' from Duration and convert to integer.

In [18]:
df['Duration'] = df['Duration'].str.replace('min', '', regex=False).str.strip().astype(int)

## Q18. Remove '$' and 'M' from Budget.

In [19]:
df['Budget'] = df['Budget'].str.replace('$', '', regex=False)\
                           .str.replace('M', '', regex=False)\
                           .astype(float)

## Q19. Remove commas from Revenue and convert numeric.

In [20]:
df['Revenue'] = pd.to_numeric(
    df['Revenue'].str.replace(',', '', regex=False),
    errors='coerce'
)

## Q20. Convert Release_Year to integer.

In [21]:
df['Release_Year'] = df['Release_Year'].astype(int)

## Q21. Convert Added_Date to datetime.

In [22]:
df['Added_Date'] = pd.to_datetime(df['Added_Date'])

/tmp/ipykernel_1445/3447673004.py:1: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['Added_Date'] = pd.to_datetime(df['Added_Date'])

## Q22. Delete rows where Title is missing.

In [23]:
df.dropna(subset=['Title'], inplace=True)

## Q23. Fill missing Rating with mean.

In [24]:
df['Rating'] = df['Rating'].fillna(df['Rating'].mean())

## Q24. Fill missing Country with mode.

In [25]:
df['Country'] = df['Country'].fillna(df['Country'].mode()[0])

## Q25. Fill missing Budget with median.

In [26]:
df['Budget'] = df['Budget'].fillna(df['Budget'].median())

## Q26. Check if any null values remain.

In [27]:
df.isnull().sum()

Movie_ID         0
Title            0
Genre            0
Release_Year     0
Rating           0
Duration         0
Director         0
Country          0
Language        59
Budget           0
Revenue         22
Platform         0
Age_Rating       0
Added_Date       0
Status           0
dtype: int64

## Q27. Save cleaned dataset as clean_movies_dataset.csv.

In [28]:
df.to_csv('clean_movies_dataset.csv', index=False)
print("File saved successfully as clean_movies_dataset.csv")

File saved successfully as clean_movies_dataset.csv

## Q28. Print Top 5 highest rated movies.

In [29]:
df.nlargest(5, 'Rating')

,Movie_ID,Title,Genre,Release_Year,Rating,Duration,Director,Country,Language,Budget,Revenue,Platform,Age_Rating,Added_Date,Status
5,6,Rrr,Sci-Fi,2021,9.8,97,Director 17,INDIA,english,76.0,263811.0,Disney+ Hotstar,PG-13,2023-02-20,Upcoming
53,54,Kgf,Drama,2024,9.7,147,Director 17,JAPAN,hindi,266.0,402764.0,Amazon Prime,U,2021-02-15,Released
81,82,Titanic,Action,2022,9.7,150,Director 1,USA,hindi,171.0,482259.0,Disney+ Hotstar,U,2022-02-12,Released
105,106,Pushpa,Sci-Fi,2022,9.7,116,Director 15,INDIA,hindi,259.0,928115.0,Amazon Prime,U/A,2025-08-24,Upcoming
298,299,Moana,Sci-Fi,2019,9.7,129,Director 3,INDIA,hindi,240.0,545580.0,Amazon Prime,U/A,2025-11-06,Released

## Q29. Count movies platform-wise.

In [30]:
df['Platform'].value_counts()

Platform
Disney+ Hotstar    100
Netflix             96
Amazon Prime        82
Name: count, dtype: int64